import { db } from '../db.js';
import { cacheExternalImage, cacheLocalImage, findLocalArtwork } from './images.js';
import type { MetadataImage, MetadataItemContext, MetadataProviderId, MetadataRecord } from './types.js';

const FIELD_MAP={title:'title',originalTitle:'original_title',sortTitle:'sort_title',year:'year',summary:'overview',runtimeMinutes:'metadata_runtime_minutes',genres:'genres',contentRating:'content_rating',originalContentRating:'original_content_rating',language:'metadata_language',country:'metadata_country',studio:'studio',premiered:'premiered',tagline:'tagline',officialUrl:'official_url',cast:'cast_json',ratings:'ratings_json',status:'series_status',network:'metadata_network',streamingService:'streaming_service',awards:'awards',trailer:'trailer_url',season:'season',episode:'episode',absoluteEpisode:'absolute_episode',aired:'aired',displaySeason:'display_season',displayEpisode:'display_episode',tags:'metadata_tags'} as const;
type MetadataField=keyof typeof FIELD_MAP|'directors'|'writers';

export function normalizeContentRating(value:unknown){
  const raw=String(value??'').trim().toUpperCase().replace(/\s+/g,'').replace(/_/g,'-');if(!raw||raw==='N/A'||raw==='NR'||raw==='UNRATED'||raw==='NOTRATED')return'ONBEKEND';
  const direct=raw.match(/(?:^|[^0-9])(6|9|12|14|16|18)(?:$|[^0-9])/);if(direct)return direct[1];
  if(['AL','G','TV-Y','TV-G','U'].includes(raw))return'AL';if(['TV-Y7','6+'].includes(raw))return'6';if(['PG','TV-PG','9+'].includes(raw))return'9';if(['PG-13','12+'].includes(raw))return'12';if(['TV-14','14+'].includes(raw))return'14';if(['R','16+'].includes(raw))return'16';if(['NC-17','TV-MA','18+','X'].includes(raw))return'18';return'ONBEKEND';
}

function jsonValue(field:MetadataField,value:any){return['genres','cast','ratings','directors','writers','tags'].includes(field)?JSON.stringify(value??[]):value??null}
function emptyValue(value:any){return value==null||value===''||value==='[]'||value==='{}'}
function valuesFor(record:MetadataRecord){
  const directors=record.crew.filter(person=>person.role?.toLowerCase().includes('director')).map(person=>person.name);const writers=record.crew.filter(person=>/(writer|screenplay|creator)/i.test(person.role||'')).map(person=>person.name);
  return{title:record.title,originalTitle:record.originalTitle,sortTitle:record.sortTitle,year:record.year,summary:record.summary,runtimeMinutes:record.runtimeMinutes,genres:record.genres,contentRating:record.contentRating?normalizeContentRating(record.contentRating):undefined,originalContentRating:record.originalContentRating||record.contentRating,language:record.language,country:record.country,studio:record.studio,premiered:record.premiered,tagline:record.tagline,officialUrl:record.officialUrl,cast:record.cast,ratings:record.ratings,status:record.status,network:record.network,streamingService:record.streamingService,awards:record.awards,trailer:record.trailer,season:record.season,episode:record.episode,absoluteEpisode:record.absoluteEpisode,aired:record.aired,displaySeason:record.displaySeason,displayEpisode:record.displayEpisode,tags:record.tags,directors,writers};
}

export async function applyMetadataRecord(mediaId:number,record:MetadataRecord,options:{mode?:'missing'|'refresh';preserveTitle?:boolean;context?:MetadataItemContext;confidence?:string}={}){
  const row=db.prepare('SELECT * FROM media_items WHERE id=?').get(mediaId) as any;if(!row)throw new Error('Media niet gevonden.');const mode=options.mode||'missing';const values=valuesFor(record) as Record<MetadataField,any>;const changed:string[]=[];const skipped:string[]=[];
  const transaction=db.transaction(()=>{
    for(const[field,column]of Object.entries(FIELD_MAP) as [Exclude<MetadataField,'directors'|'writers'>,string][])apply(field,column);
    apply('directors','directors');apply('writers','writers');
    for(const[provider,id]of Object.entries(record.externalIds)){if(!id)continue;const providerName=provider==='legacyTmdb'?'legacy_tmdb':provider;db.prepare(`INSERT INTO metadata_external_ids(media_id,provider,external_id,legacy) VALUES(?,?,?,?) ON CONFLICT(media_id,provider) DO UPDATE SET external_id=excluded.external_id,legacy=excluded.legacy,updated_at=CURRENT_TIMESTAMP`).run(mediaId,providerName,String(id),Number(provider==='legacyTmdb'))}
    db.prepare('UPDATE media_items SET metadata_provider=?,metadata_last_refreshed=CURRENT_TIMESTAMP,metadata_match_confidence=?,metadata_needs_review=? WHERE id=?').run(record.provider,options.confidence||record.confidence||'very_certain',Number((options.confidence||record.confidence)==='review'),mediaId);
    if(record.cast.length||record.crew.length){db.prepare('DELETE FROM metadata_credits WHERE media_id=? AND provider=?').run(mediaId,record.provider);const insert=db.prepare('INSERT OR IGNORE INTO metadata_credits(media_id,credit_type,name,role,character_name,sort_order,provider) VALUES(?,?,?,?,?,?,?)');record.cast.forEach((person,index)=>insert.run(mediaId,'cast',person.name,person.role||'Actor',person.character||null,person.order??index,record.provider));record.crew.forEach((person,index)=>insert.run(mediaId,'crew',person.name,person.role||null,null,person.order??index,record.provider))}
    if(record.ratings.length){const insert=db.prepare(`INSERT INTO metadata_ratings(media_id,source,value,max_value,votes,provider,fetched_at) VALUES(?,?,?,?,?,?,CURRENT_TIMESTAMP) ON CONFLICT(media_id,source) DO UPDATE SET value=excluded.value,max_value=excluded.max_value,votes=excluded.votes,provider=excluded.provider,fetched_at=CURRENT_TIMESTAMP`);for(const rating of record.ratings)insert.run(mediaId,rating.source,rating.value,rating.maxValue,rating.votes??null,record.provider)}
    if(record.collection&&record.provider==='local_nfo'){let collection=db.prepare('SELECT id FROM collections WHERE owner_id IS NULL AND name=?').get(record.collection) as any;if(!collection){const result=db.prepare('INSERT INTO collections(owner_id,name,description,is_public) VALUES(NULL,?,\'\',1)').run(record.collection);collection={id:Number(result.lastInsertRowid)}}db.prepare('INSERT OR IGNORE INTO collection_items(collection_id,media_id,position) VALUES(?,?,(SELECT COUNT(*) FROM collection_items WHERE collection_id=?))').run(collection.id,mediaId,collection.id)}
    function apply(field:MetadataField,column:string){const incoming=jsonValue(field,values[field]);if(incoming===undefined||incoming===null||incoming===''||incoming==='[]')return;if(options.preserveTitle&&['title','sortTitle'].includes(field)){skipped.push(field);return}const state=db.prepare('SELECT provider,manually_modified manual,auto_overwrite autoOverwrite FROM metadata_field_state WHERE media_id=? AND field_name=?').get(mediaId,field) as any;if(state?.manual||(state?.autoOverwrite===0&&state?.provider!==record.provider)){skipped.push(field);return}const current=row[column];if(mode==='missing'&&!emptyValue(current)){skipped.push(field);return}if(String(current??'')===String(incoming??''))return;db.prepare(`UPDATE media_items SET ${column}=?,updated_at=CURRENT_TIMESTAMP WHERE id=?`).run(incoming,mediaId);db.prepare('INSERT INTO metadata_history(media_id,field_name,previous_value_json,new_value_json,provider,manual) VALUES(?,?,?,?,?,0)').run(mediaId,field,JSON.stringify(current),JSON.stringify(incoming),record.provider);db.prepare(`INSERT INTO metadata_field_state(media_id,field_name,provider,value_json,fetched_at,manually_modified,auto_overwrite) VALUES(?,?,?, ?,CURRENT_TIMESTAMP,0,?) ON CONFLICT(media_id,field_name) DO UPDATE SET provider=excluded.provider,value_json=excluded.value_json,fetched_at=CURRENT_TIMESTAMP,auto_overwrite=excluded.auto_overwrite WHERE manually_modified=0 AND (auto_overwrite=1 OR provider=excluded.provider)`).run(mediaId,field,record.provider,JSON.stringify(incoming),Number(record.provider!=='local_nfo'));changed.push(field)}
  });transaction();
  await cacheRecordImages(mediaId,record,options.context);
  return{mediaId,provider:record.provider,changed,skipped};
}

async function cacheRecordImages(mediaId:number,record:MetadataRecord,context?:MetadataItemContext){
  if(context?.filePath&&context.sourcePath){const local=findLocalArtwork({filePath:context.filePath,sourcePath:context.sourcePath,kind:context.mediaType==='movie'?'movie':'episode',season:context.season});for(const[type,file]of Object.entries(local))try{await cacheLocalImage(mediaId,type as MetadataImage['type'],file,context.sourcePath)}catch{}}
  for(const image of record.images){try{if(image.localPath&&context?.sourcePath)await cacheLocalImage(mediaId,image.type,image.localPath,context.sourcePath);else if(image.url)await cacheExternalImage(mediaId,image,record.provider)}catch{/* Een mislukte afbeelding mag metadata en scans niet stoppen. */}}
}

export function applyManualMetadata(mediaId:number,changes:Record<string,unknown>){
  const allowed:Record<string,string>={title:'title',originalTitle:'original_title',sortTitle:'sort_title',year:'year',overview:'overview',runtimeMinutes:'metadata_runtime_minutes',genres:'genres',contentRating:'content_rating',edition:'edition',tagline:'tagline',language:'metadata_language',country:'metadata_country',studio:'studio',directors:'directors',writers:'writers',cast:'cast_json',ratings:'ratings_json',premiered:'premiered',officialUrl:'official_url',status:'series_status',network:'metadata_network',streamingService:'streaming_service',awards:'awards',trailer:'trailer_url',season:'season',episode:'episode',absoluteEpisode:'absolute_episode',aired:'aired',displaySeason:'display_season',displayEpisode:'display_episode',tags:'metadata_tags'};const row=db.prepare('SELECT * FROM media_items WHERE id=?').get(mediaId) as any;if(!row)throw Object.assign(new Error('Media niet gevonden.'),{status:404});const updated:Record<string,unknown>={};
  const transaction=db.transaction(()=>{
    for(const[field,value]of Object.entries(changes)){if(value===undefined)continue;const column=allowed[field];if(!column)continue;const stored=['genres','directors','writers','cast','ratings','tags'].includes(field)?JSON.stringify(Array.isArray(value)?value:[]):field==='contentRating'?normalizeContentRating(value):value??null;const previous=row[column];if(String(previous??'')===String(stored??''))continue;db.prepare(`UPDATE media_items SET ${column}=?,updated_at=CURRENT_TIMESTAMP WHERE id=?`).run(stored,mediaId);db.prepare('INSERT INTO metadata_history(media_id,field_name,previous_value_json,new_value_json,provider,manual) VALUES(?,?,?,?,\'manual\',1)').run(mediaId,field,JSON.stringify(previous),JSON.stringify(stored));db.prepare(`INSERT INTO metadata_field_state(media_id,field_name,provider,value_json,fetched_at,manually_modified,auto_overwrite) VALUES(?,?,\'manual\',?,CURRENT_TIMESTAMP,1,0) ON CONFLICT(media_id,field_name) DO UPDATE SET provider='manual',value_json=excluded.value_json,fetched_at=CURRENT_TIMESTAMP,manually_modified=1,auto_overwrite=0`).run(mediaId,field,JSON.stringify(stored));updated[field]=value}
    for(const[field,provider]of [['imdbId','imdb'],['tvmazeId','tvmaze']] as const){if(changes[field]===undefined)continue;const raw=String(changes[field]??'').trim();if(raw&&(provider==='imdb'?!/^tt\d{7,10}$/i.test(raw):!/^[1-9]\d*$/.test(raw)))throw Object.assign(new Error(provider==='imdb'?'IMDb-ID moet de vorm tt1234567 hebben.':'TVmaze-ID moet een positief nummer zijn.'),{status:400});const normalized=provider==='imdb'?raw.toLowerCase():raw;const previous=(db.prepare('SELECT external_id externalId FROM metadata_external_ids WHERE media_id=? AND provider=?').get(mediaId,provider) as any)?.externalId||null;if(String(previous??'')===normalized)continue;if(normalized){db.prepare(`INSERT INTO metadata_external_ids(media_id,provider,external_id,legacy,updated_at) VALUES(?,?,?,0,CURRENT_TIMESTAMP) ON CONFLICT(media_id,provider) DO UPDATE SET external_id=excluded.external_id,legacy=0,updated_at=CURRENT_TIMESTAMP`).run(mediaId,provider,normalized);if(provider==='imdb')db.prepare(`INSERT INTO metadata_external_ids(media_id,provider,external_id,legacy,updated_at) VALUES(?,\'omdb\',?,0,CURRENT_TIMESTAMP) ON CONFLICT(media_id,provider) DO UPDATE SET external_id=excluded.external_id,legacy=0,updated_at=CURRENT_TIMESTAMP`).run(mediaId,normalized)}else{db.prepare('DELETE FROM metadata_external_ids WHERE media_id=? AND provider=?').run(mediaId,provider);if(provider==='imdb')db.prepare("DELETE FROM metadata_external_ids WHERE media_id=? AND provider='omdb'").run(mediaId)}db.prepare('INSERT INTO metadata_history(media_id,field_name,previous_value_json,new_value_json,provider,manual) VALUES(?,?,?,?,\'manual\',1)').run(mediaId,field,JSON.stringify(previous),JSON.stringify(normalized||null));db.prepare(`INSERT INTO metadata_field_state(media_id,field_name,provider,value_json,fetched_at,manually_modified,auto_overwrite) VALUES(?,?,\'manual\',?,CURRENT_TIMESTAMP,1,0) ON CONFLICT(media_id,field_name) DO UPDATE SET provider='manual',value_json=excluded.value_json,fetched_at=CURRENT_TIMESTAMP,manually_modified=1,auto_overwrite=0`).run(mediaId,field,JSON.stringify(normalized||null));updated[field]=normalized||null}
    db.prepare("UPDATE media_items SET metadata_provider=COALESCE(metadata_provider,'manual') WHERE id=?").run(mediaId)
  });transaction();return updated;
}

export function setMetadataFieldLock(mediaId:number,field:string,locked:boolean){const state=db.prepare('SELECT value_json valueJson,provider FROM metadata_field_state WHERE media_id=? AND field_name=?').get(mediaId,field) as any;db.prepare(`INSERT INTO metadata_field_state(media_id,field_name,provider,value_json,manually_modified,auto_overwrite) VALUES(?,?,COALESCE(?,\'manual\'),?,?,?) ON CONFLICT(media_id,field_name) DO UPDATE SET manually_modified=excluded.manually_modified,auto_overwrite=excluded.auto_overwrite`).run(mediaId,field,state?.provider||'manual',state?.valueJson||null,Number(locked),Number(!locked));}
export function metadataHistory(mediaId:number){return db.prepare('SELECT id,field_name fieldName,previous_value_json previousValue,new_value_json newValue,provider,manual,changed_at changedAt FROM metadata_history WHERE media_id=? ORDER BY id DESC LIMIT 200').all(mediaId)}
export function restoreMetadataHistory(mediaId:number,historyId:number){const entry=db.prepare('SELECT * FROM metadata_history WHERE id=? AND media_id=?').get(historyId,mediaId) as any;if(!entry)throw Object.assign(new Error('Metadatawijziging niet gevonden.'),{status:404});let previous;try{previous=JSON.parse(entry.previous_value_json)}catch{previous=null}const field=entry.field_name==='summary'?'overview':entry.field_name;return applyManualMetadata(mediaId,{[field]:previous})}
export function metadataFieldStates(mediaId:number){return db.prepare('SELECT field_name fieldName,provider,fetched_at fetchedAt,manually_modified manuallyModified,auto_overwrite autoOverwrite FROM metadata_field_state WHERE media_id=? ORDER BY field_name').all(mediaId)}

export const applyInternals={valuesFor,emptyValue,jsonValue,FIELD_MAP};
