import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import sharp from 'sharp';
import { afterAll,beforeAll,describe,expect,it } from 'vitest';

const root=fs.mkdtempSync(path.join(os.tmpdir(),'thuishub-metadata-'));
fs.writeFileSync(path.join(root,'.migration-from-huiskamer.json'),'{}');
process.env.THUIS_HUB_ROOT_DIR=root;process.env.THUIS_HUB_DATA_DIR=path.join(root,'data');process.env.THUIS_HUB_BACKUP_DIR=path.join(root,'backups');process.env.THUIS_HUB_LOG_DIR=path.join(root,'logs');process.env.OMDB_API_KEY='test1234';

const database=await import('../db.js');
const{db}=database;
const{TvmazeProvider,tvmazeInternals}=await import('./providers/tvmaze.js');
const{OmdbProvider,omdbInternals}=await import('./providers/omdb.js');
const{nfoInternals}=await import('./providers/local-nfo.js');
const{sanitizeExternalText}=await import('./sanitize.js');
const{chooseMetadataMatch}=await import('./matching.js');
const{applyManualMetadata,applyMetadataRecord}=await import('./apply.js');
const{blockedNetworkAddress,cacheExternalImage,cacheLocalImage,findLocalArtwork,validateExternalImageUrl}=await import('./images.js');
const{redactedProviderUrl,requestProviderJson}=await import('./http.js');
const{embeddedInternals}=await import('./providers/embedded.js');
const{enqueueMetadata,metadataProviders,migrateLegacyTmdbMetadata,processMetadataQueue}=await import('./index.js');

let sourceId=0,mediaId=0;const mediaRoot=path.join(root,'media');
beforeAll(()=>{fs.mkdirSync(mediaRoot,{recursive:true});sourceId=Number(db.prepare("INSERT INTO sources(name,path,kind) VALUES('Films',?,'movies')").run(mediaRoot).lastInsertRowid);const file=path.join(mediaRoot,'Test Movie (2024).mkv');fs.writeFileSync(file,'test');mediaId=Number(db.prepare("INSERT INTO media_items(source_id,kind,title,sort_title,year,file_path,size) VALUES(?,'movie','Test Movie','test movie',2024,?,4)").run(sourceId,file).lastInsertRowid)});
afterAll(()=>{delete process.env.OMDB_API_KEY;db.close();fs.rmSync(root,{recursive:true,force:true})});

describe('provider-normalisatie en matching',()=>{
  it('verwijdert uitvoerbare HTML uit externe tekst',()=>expect(sanitizeExternalText('<p>Hallo &amp; welkom</p><script>steel()</script>')).toBe('Hallo & welkom'));
  it('normaliseert TVmaze-series en afleveringen zonder HTML',()=>{const show=tvmazeInternals.mapShow({id:7,name:'Serie',premiered:'2024-01-02',summary:'<b>Samenvatting</b>',genres:['Drama'],externals:{imdb:'tt1234567'}});expect(show).toMatchObject({provider:'tvmaze',providerId:'7',summary:'Samenvatting',year:2024,externalIds:{imdb:'tt1234567'}});expect(tvmazeInternals.mapEpisode({id:9,name:'Pilot',season:1,number:2,airdate:'2024-01-03'},'7')).toMatchObject({season:1,episode:2,aired:'2024-01-03'})});
  it('leest de officiële TVmaze-seizoensroute',async()=>{let url='';const provider=new TvmazeProvider({fetcher:(async input=>{url=String(input);return new Response(JSON.stringify([{id:22,number:1,episodeOrder:10,premiereDate:'2024-01-01'}]),{status:200,headers:{'content-type':'application/json'}})}) as typeof fetch});expect(await provider.getSeasons('7')).toMatchObject([{providerId:'22',number:1,episodeOrder:10}]);expect(url).toContain('/shows/7/seasons')});
  it('normaliseert OMDb-details, ratings en classificatiebron',()=>{const movie=omdbInternals.mapOmdb({Response:'True',imdbID:'tt0133093',Title:'The Matrix',Type:'movie',Year:'1999',Runtime:'136 min',Rated:'R',Genre:'Action, Sci-Fi',imdbRating:'8.7',imdbVotes:'2,100,000'});expect(movie).toMatchObject({provider:'omdb',runtimeMinutes:136,contentRating:'R',genres:['Action','Sci-Fi']});expect(movie?.ratings[0]).toMatchObject({source:'IMDb',value:8.7,maxValue:10,votes:2100000})});
  it('kiest alleen een unieke exacte titel+jaar automatisch',()=>{const base={mediaType:'movie' as const,title:'Dune',year:2021,genres:[],cast:[],crew:[],ratings:[],images:[],externalIds:{},provider:'omdb' as const,providerId:'tt1160419'};expect(chooseMetadataMatch({title:'Dune',year:2021},[base]).confidence).toBe('very_certain');expect(chooseMetadataMatch({title:'Dune',year:2021},[base,{...base,providerId:'tt2'}]).confidence).toBe('review')});
  it('leest ingebedde tags zonder bestandsinhoud te versturen',()=>expect(embeddedInternals.embeddedRecord({title:'Bestand',mediaType:'movie'},JSON.stringify({format:{tags:{title:'Tagtitel',genre:'Drama, Actie',description:'<b>Plot</b>'}}}))).toMatchObject({title:'Tagtitel',genres:['Drama','Actie'],summary:'Plot'}));
  it('doorloopt TVmaze zoeken, serie, seizoenen, afleveringen, cast, crew en afbeeldingen',async()=>{const fetcher=(async input=>{const url=new URL(String(input));let payload:any={};if(url.pathname==='/search/shows')payload=[{show:{id:7001,name:'Dubbele serie',premiered:'2024-01-01',language:'Nederlands',network:{name:'NPO'},genres:[],externals:{}}},{show:{id:7002,name:'Dubbele serie',premiered:'2023-01-01',webChannel:{name:'Stream'},genres:[],externals:{}}}];else if(url.pathname==='/shows/7001')payload={id:7001,name:'Dubbele serie',premiered:'2024-01-01',genres:['Drama'],externals:{imdb:'tt7000001'}};else if(url.pathname==='/shows/7001/seasons')payload=[{id:7101,number:1,episodeOrder:2}];else if(url.pathname==='/shows/7001/episodes')payload=[{id:7201,name:'Pilot',season:1,number:1,airdate:'2024-01-02'}];else if(url.pathname==='/shows/7001/cast')payload=[{person:{name:'Acteur'},character:{name:'Rol'}}];else if(url.pathname==='/shows/7001/crew')payload=[{person:{name:'Maker'},type:'Creator'}];else if(url.pathname==='/shows/7001/images')payload=[{type:'poster',main:true,resolutions:{original:{url:'https://example.test/poster.jpg',width:1000,height:1500}}}];else return new Response('{}',{status:404});return new Response(JSON.stringify(payload),{status:200,headers:{'content-type':'application/json'}})}) as typeof fetch;const provider=new TvmazeProvider({fetcher});const results=await provider.searchSeries({title:'Dubbele serie provider-test'});expect(results).toHaveLength(2);expect(chooseMetadataMatch({title:'Dubbele serie',year:2024,mediaType:'series'},results).confidence).toBe('review');expect(await provider.getSeries('7001')).toMatchObject({title:'Dubbele serie',externalIds:{imdb:'tt7000001'}});expect(await provider.getSeasons('7001')).toMatchObject([{providerId:'7101',number:1,episodeOrder:2}]);expect(await provider.getEpisode('7001',1,1)).toMatchObject({title:'Pilot',aired:'2024-01-02'});expect(await provider.getCast('7001')).toMatchObject([{name:'Acteur',character:'Rol'}]);expect(await provider.getCrew('7001')).toMatchObject([{name:'Maker',role:'Creator'}]);expect(await provider.getImages('7001')).toMatchObject([{type:'poster',primary:true}])});
  it('behandelt een ontbrekende TVmaze-serie als geen resultaat',async()=>{const provider=new TvmazeProvider({fetcher:(async()=>new Response('{}',{status:404})) as typeof fetch});expect(await provider.findByExternalId({imdb:'tt7000999'})).toBeNull()});
});

describe('netwerkproviders en caching',()=>{
  it('gebruikt de vaste User-Agent en wacht bij een TVmaze 429',async()=>{let calls=0;let waited=0;const fetcher=async(_input:any,init?:RequestInit)=>{expect((init?.headers as any)['user-agent']).toMatch(/^ThuisHub\//);calls++;return calls===1?new Response('{}',{status:429,headers:{'retry-after':'1'}}):new Response(JSON.stringify({id:1,name:'Under the Dome',genres:[],externals:{}}),{status:200,headers:{'content-type':'application/json'}})};const provider=new TvmazeProvider({fetcher:fetcher as typeof fetch,sleep:async ms=>{waited=ms}});expect((await provider.getSeries('1'))?.title).toBe('Under the Dome');expect(calls).toBe(2);expect(waited).toBe(1000)});
  it('stuurt de OMDb-key wel naar OMDb maar redigeert hem uit URLs en foutmeldingen',async()=>{let requested='';const provider=new OmdbProvider({fetcher:(async input=>{requested=String(input);return new Response(JSON.stringify({Response:'True',Search:[{Title:'Test Movie',Year:'2024',imdbID:'tt1234567',Type:'movie'}]}),{status:200,headers:{'content-type':'application/json'}})}) as typeof fetch});expect((await provider.searchMovies({title:'Test Movie',year:2024}))[0].providerId).toBe('tt1234567');expect(requested).toContain('apikey=test1234');expect(redactedProviderUrl(new URL(requested))).not.toContain('test1234')});
  it('werkt zonder OMDb-key en meldt een ongeldige key veilig',async()=>{delete process.env.OMDB_API_KEY;await expect(new OmdbProvider().getMovie('tt0133093')).rejects.toThrow(/optioneel|API-key/);process.env.OMDB_API_KEY='badkey';const invalid=new OmdbProvider({fetcher:(async()=>new Response(JSON.stringify({Response:'False',Error:'Invalid API key!'}),{status:200,headers:{'content-type':'application/json'}})) as typeof fetch});await expect(invalid.getMovie('tt0133093')).rejects.toThrow(/Invalid API key/);process.env.OMDB_API_KEY='test1234'});
  it('begrensd retries timeouts, weigert corrupte JSON en gebruikt cache offline',async()=>{let calls=0;const timeout=(async()=>{calls++;throw Object.assign(new Error('timeout'),{name:'TimeoutError'})}) as typeof fetch;await expect(requestProviderJson({provider:'tvmaze',url:new URL('https://api.tvmaze.com/shows/999991'),cacheKey:'timeout-test',fetcher:timeout,sleep:async()=>{}})).rejects.toThrow(/timeout/);expect(calls).toBe(3);await expect(requestProviderJson({provider:'tvmaze',url:new URL('https://api.tvmaze.com/shows/999992'),cacheKey:'corrupt-test',fetcher:(async()=>new Response('{',{status:200})) as typeof fetch})).rejects.toThrow(/JSON/);const good=(async()=>new Response('{"ok":true}',{status:200,headers:{'content-type':'application/json'}})) as typeof fetch;expect(await requestProviderJson({provider:'tvmaze',url:new URL('https://api.tvmaze.com/shows/999993'),cacheKey:'offline-cache',fetcher:good})).toMatchObject({ok:true});expect(await requestProviderJson({provider:'tvmaze',url:new URL('https://api.tvmaze.com/shows/999993'),cacheKey:'offline-cache',fetcher:(async()=>{throw new Error('offline')}) as typeof fetch})).toMatchObject({ok:true})});
  it('zoekt OMDb op titel en jaar en haalt details via IMDb-ID op',async()=>{const fetcher=(async input=>{const url=new URL(String(input));const id=url.searchParams.get('i');const payload=id?{Response:'True',imdbID:id,Title:id==='tt7654321'?'Zonder poster':'Unieke mockfilm',Type:'movie',Year:'2025',Released:'01 Jan 2025',Runtime:'101 min',Genre:'Drama',Poster:'N/A'}:{Response:'True',Search:[{Title:'Unieke mockfilm',Year:'2025',imdbID:'tt7001234',Type:'movie',Poster:'N/A'}]};return new Response(JSON.stringify(payload),{status:200,headers:{'content-type':'application/json'}})}) as typeof fetch;const provider=new OmdbProvider({fetcher});expect(await provider.searchMovies({title:'Unieke mockfilm provider-test',year:2025})).toMatchObject([{providerId:'tt7001234',year:2025}]);expect(await provider.getMovie('tt7001234')).toMatchObject({title:'Unieke mockfilm',runtimeMinutes:101});expect(await provider.findByExternalId({imdb:'tt7001234'})).toMatchObject({providerId:'tt7001234'});expect((await provider.getMovie('tt7654321'))?.images).toHaveLength(0)});
  it('meldt OMDb niet gevonden, corrupte JSON, timeout en lokale daglimiet',async()=>{const missing=new OmdbProvider({fetcher:(async()=>new Response(JSON.stringify({Response:'False',Error:'Movie not found!'}),{status:200,headers:{'content-type':'application/json'}})) as typeof fetch});await expect(missing.getMovie('tt7002222')).rejects.toThrow(/not found/i);const corrupt=new OmdbProvider({fetcher:(async()=>new Response('{',{status:200})) as typeof fetch});await expect(corrupt.getMovie('tt7002223')).rejects.toThrow(/JSON/);let calls=0;const timeout=new OmdbProvider({fetcher:(async()=>{calls++;throw Object.assign(new Error('timeout'),{name:'TimeoutError'})}) as typeof fetch,sleep:async()=>{}});await expect(timeout.getMovie('tt7002224')).rejects.toThrow(/timeout/);expect(calls).toBe(3);database.setSetting('omdbLocalDailyLimit','1');const day=new Date().toISOString().slice(0,10);db.prepare(`INSERT INTO metadata_provider_usage(provider,usage_date,requests) VALUES('omdb',?,1) ON CONFLICT(provider,usage_date) DO UPDATE SET requests=1`).run(day);await expect(new OmdbProvider().getMovie('tt7002225')).rejects.toThrow(/daglimiet/);db.prepare("DELETE FROM metadata_provider_usage WHERE provider='omdb' AND usage_date=?").run(day);database.setSetting('omdbLocalDailyLimit','1000')});
});

describe('NFO, afbeeldingen en SSRF-bescherming',()=>{
  it('leest Kodi-NFO en blokkeert lokale paden buiten de bibliotheek',()=>{const nfo=path.join(mediaRoot,'movie.nfo');fs.writeFileSync(nfo,'<movie><title>Lokale film</title><plot><![CDATA[Veilige tekst]]></plot><uniqueid type="imdb">tt1234567</uniqueid><thumb>../geheim.jpg</thumb><genre>Drama</genre></movie>');const record=nfoInternals.parseNfoFile(nfo,mediaRoot);expect(record).toMatchObject({title:'Lokale film',externalIds:{imdb:'tt1234567'},genres:['Drama']});expect(record?.images).toHaveLength(0)});
  it('leest tvshow- en aflevering-NFO plus lokale poster en achtergrond',async()=>{const showDir=path.join(mediaRoot,'Serie');const seasonDir=path.join(showDir,'Season 01');fs.mkdirSync(seasonDir,{recursive:true});const tvshow=path.join(showDir,'tvshow.nfo');const episode=path.join(seasonDir,'Serie.S01E02.nfo');fs.writeFileSync(tvshow,'<tvshow><title>Serie</title><status>Running</status><uniqueid type="tvmaze">77</uniqueid></tvshow>');fs.writeFileSync(episode,'<episodedetails><title>Tweede</title><season>1</season><episode>2</episode><displayseason>1</displayseason><displayepisode>2</displayepisode><aired>2024-01-02</aired></episodedetails>');expect(nfoInternals.parseNfoFile(tvshow,mediaRoot)).toMatchObject({mediaType:'series',title:'Serie',externalIds:{tvmaze:'77'}});expect(nfoInternals.parseNfoFile(episode,mediaRoot)).toMatchObject({mediaType:'episode',season:1,episode:2,displaySeason:1,displayEpisode:2});const poster=path.join(showDir,'poster.jpg'),fanart=path.join(showDir,'fanart.jpg');const pixels=await sharp({create:{width:2,height:3,channels:3,background:'#111'}}).jpeg().toBuffer();fs.writeFileSync(poster,pixels);fs.writeFileSync(fanart,pixels);expect(findLocalArtwork({filePath:path.join(seasonDir,'Serie.S01E02.mkv'),sourcePath:mediaRoot,kind:'episode',season:1})).toMatchObject({poster,backdrop:fanart})});
  it('blokkeert privé-, loopback- en link-local adressen',async()=>{for(const address of ['127.0.0.1','10.0.0.1','192.168.1.1','169.254.1.1','::1','fd00::1'])expect(blockedNetworkAddress(address)).toBe(true);await expect(validateExternalImageUrl('http://voorbeeld.test/a.jpg',async()=>[{address:'127.0.0.1',family:4}] as any)).rejects.toThrow(/geblokkeerd/)});
  it('cachet alleen geverifieerde rasterafbeeldingen met een maximumgrootte',async()=>{const png=await sharp({create:{width:4,height:4,channels:3,background:'#ff0000'}}).png().toBuffer();const fetcher=(async()=>new Response(png,{status:200,headers:{'content-type':'image/png','content-length':String(png.length)}})) as typeof fetch;const image=await cacheExternalImage(mediaId,{type:'poster',url:'https://8.8.8.8/poster.png'},'omdb',fetcher);expect(fs.existsSync(image.localPath)).toBe(true);const preview=await cacheExternalImage(mediaId,{type:'backdrop',url:'https://8.8.8.8/preview.png'},'omdb',fetcher,false,false);expect(db.prepare('SELECT selected FROM metadata_images WHERE id=?').get(preview.id)).toMatchObject({selected:0});const svg=(async()=>new Response('<svg/>',{status:200,headers:{'content-type':'image/svg+xml'}})) as typeof fetch;await expect(cacheExternalImage(mediaId,{type:'poster',url:'https://8.8.8.8/a.svg'},'omdb',svg)).rejects.toThrow(/ondersteund|toegestaan/) });
  it('geeft lokale artwork voorrang boven later opgehaalde providerafbeeldingen',async()=>{const localFile=path.join(mediaRoot,'priority-poster.png');const localBytes=await sharp({create:{width:4,height:6,channels:3,background:'#00ff00'}}).png().toBuffer();fs.writeFileSync(localFile,localBytes);const local=await cacheLocalImage(mediaId,'poster',localFile,mediaRoot);const remoteBytes=await sharp({create:{width:4,height:6,channels:3,background:'#0000ff'}}).png().toBuffer();const fetcher=(async()=>new Response(remoteBytes,{status:200,headers:{'content-type':'image/png'}})) as typeof fetch;await cacheExternalImage(mediaId,{type:'poster',url:'https://8.8.4.4/new-poster.png'},'omdb',fetcher);expect(db.prepare('SELECT id,provider FROM metadata_images WHERE media_id=? AND image_type=\'poster\' AND selected=1').get(mediaId)).toMatchObject({id:local.id,provider:'local_nfo'})});
  it('vangt corrupte NFO af en houdt een externe NFO-afbeelding als te valideren URL',()=>{const broken=path.join(mediaRoot,'broken.nfo');fs.writeFileSync(broken,'<movie><title>Onvolledig');expect(()=>nfoInternals.parseNfoFile(broken,mediaRoot)).toThrow(/ongeldige XML|hoofdstructuur/);const external=path.join(mediaRoot,'external.nfo');fs.writeFileSync(external,'<movie><title>Externe afbeelding</title><poster>https://images.example.test/poster.jpg</poster></movie>');expect(nfoInternals.parseNfoFile(external,mediaRoot)?.images).toMatchObject([{type:'poster',url:'https://images.example.test/poster.jpg'}])});
});

describe('provider-fallback',()=>{
  it('gebruikt lokale NFO wanneer OMDb tijdelijk niet bereikbaar is',async()=>{const file=path.join(mediaRoot,'Fallback Movie (2025).mkv');fs.writeFileSync(file,'test');fs.writeFileSync(path.join(mediaRoot,'Fallback Movie (2025).nfo'),'<movie><title>Lokale fallbacktitel</title><year>2025</year></movie>');const fallbackId=Number(db.prepare("INSERT INTO media_items(source_id,kind,title,sort_title,year,file_path,size) VALUES(?,'movie','Fallback Movie','fallback movie',2025,?,4)").run(sourceId,file).lastInsertRowid);const original=metadataProviders.omdb.searchMovies.bind(metadataProviders.omdb);metadataProviders.omdb.searchMovies=async()=>{throw new Error('provider offline')};try{enqueueMetadata(fallbackId,'fallback-test','omdb');expect(await processMetadataQueue(1)).toMatchObject({processed:1,errors:0});expect(db.prepare('SELECT title,metadata_provider FROM media_items WHERE id=?').get(fallbackId)).toMatchObject({title:'Lokale fallbacktitel',metadata_provider:'local_nfo'});expect(db.prepare('SELECT status FROM metadata_queue WHERE media_id=?').get(fallbackId)).toMatchObject({status:'completed'})}finally{metadataProviders.omdb.searchMovies=original}});
});

describe('handmatige locks en migratie',()=>{
  it('laat een provider een handmatig gewijzigd veld niet overschrijven',async()=>{applyManualMetadata(mediaId,{title:'Mijn titel'});await applyMetadataRecord(mediaId,{mediaType:'movie',title:'Provider titel',genres:['Drama'],cast:[],crew:[],ratings:[],images:[],externalIds:{imdb:'tt1234567'},provider:'omdb',providerId:'tt1234567'},{mode:'refresh'});expect((db.prepare('SELECT title,genres FROM media_items WHERE id=?').get(mediaId) as any).title).toBe('Mijn titel')});
  it('valideert en vergrendelt handmatig ingevoerde externe IDs',()=>{applyManualMetadata(mediaId,{imdbId:'TT7654321',tvmazeId:'7654'});expect(db.prepare("SELECT external_id FROM metadata_external_ids WHERE media_id=? AND provider='imdb'").get(mediaId)).toMatchObject({external_id:'tt7654321'});expect(db.prepare("SELECT external_id FROM metadata_external_ids WHERE media_id=? AND provider='omdb'").get(mediaId)).toMatchObject({external_id:'tt7654321'});expect(db.prepare("SELECT external_id FROM metadata_external_ids WHERE media_id=? AND provider='tvmaze'").get(mediaId)).toMatchObject({external_id:'7654'});expect(db.prepare("SELECT manually_modified,auto_overwrite FROM metadata_field_state WHERE media_id=? AND field_name='imdbId'").get(mediaId)).toMatchObject({manually_modified:1,auto_overwrite:0});expect(()=>applyManualMetadata(mediaId,{tvmazeId:'0'})).toThrow(/positief nummer/)});
  it('maakt vóór legacy-migratie een back-up en bewaart voortgang, favorieten en collecties',async()=>{const userId=Number(db.prepare("INSERT INTO users(username,password_hash,role) VALUES('Migratietest','test-hash','user')").run().lastInsertRowid);db.prepare('INSERT INTO progress(user_id,media_id,position,duration,completed) VALUES(?,?,?,?,?)').run(userId,mediaId,321,600,0);db.prepare('INSERT INTO media_user_state(user_id,media_id,favorite,watchlist,watched,rating) VALUES(?,?,?,?,?,?)').run(userId,mediaId,1,1,0,8.5);const collectionId=Number(db.prepare("INSERT INTO collections(owner_id,name) VALUES(?,'Bewaarde collectie')").run(userId).lastInsertRowid);db.prepare('INSERT INTO collection_items(collection_id,media_id,position) VALUES(?,?,?)').run(collectionId,mediaId,2);db.prepare('UPDATE media_items SET tmdb_id=321,overview=\'Bestaand\' WHERE id=?').run(mediaId);database.setSetting('tmdbToken','mag-niet-blijven');const report=await migrateLegacyTmdbMetadata() as any;expect(report.status).toBe('completed');expect(report.tmdbRequests).toBe(0);expect(fs.existsSync(path.join(root,'backups',report.backup))).toBe(true);expect(db.prepare("SELECT external_id FROM metadata_external_ids WHERE media_id=? AND provider='legacy_tmdb'").get(mediaId)).toMatchObject({external_id:'321'});expect(db.prepare('SELECT position,duration,completed FROM progress WHERE user_id=? AND media_id=?').get(userId,mediaId)).toMatchObject({position:321,duration:600,completed:0});expect(db.prepare('SELECT favorite,watchlist,watched,rating FROM media_user_state WHERE user_id=? AND media_id=?').get(userId,mediaId)).toMatchObject({favorite:1,watchlist:1,watched:0,rating:8.5});expect(db.prepare('SELECT position FROM collection_items WHERE collection_id=? AND media_id=?').get(collectionId,mediaId)).toMatchObject({position:2});expect(database.getSetting('tmdbToken')).toBe('')});
});
