(function(){
var root=document.getElementById('app'),prefs={server:localStorage.server||'',token:localStorage.deviceToken||''},currentMediaId=0;
function request(path,method,body,device){return fetch(prefs.server+path,{method:method||'GET',headers:Object.assign({'Content-Type':'application/json'},device&&prefs.token?{'Authorization':'Device '+prefs.token}:{}),body:body?JSON.stringify(body):undefined}).then(function(r){return r.json().then(function(data){if(!r.ok)throw new Error(data.error||('Serverfout '+r.status));return data})})}
function capabilities(){var width=screen.width||1920,height=screen.height||1080,hdr=[];try{if(webapis.productinfo.isUdPanelSupported())hdr.push('hdr10');if(webapis.productinfo.isHdrTvSupport())hdr.push('hdr10','hdr10plus','hlg')}catch(e){};return{maxWidth:width,maxHeight:height,maxFrameRate:60,maxBitrateMbps:80,containers:['mp4','mpegts','mkv'],videoCodecs:['h264','hevc','vp9','av1'],maxBitDepth:10,hdrFormats:['sdr'].concat(hdr.filter(function(x,i,a){return a.indexOf(x)===i})),dolbyVisionProfiles:[],audioCodecs:['aac','ac3','eac3','dts'],maxAudioChannels:8,passthrough:true,atmos:true,trueHd:false,eac3:true,dts:true,subtitleFormats:['srt','webvtt'],arc:'unknown'}}
function pair(){root.innerHTML='<section class="pair"><div><h2>Koppel deze Samsung-tv</h2><input id="server" value="'+prefs.server+'" placeholder="http://192.168.1.10:8788"><button id="pair">Koppelcode maken</button><div class="code" id="code"></div><p id="message">Gebruik de privé-LAN-streamingpoort van ThuisHub.</p></div></section>';document.getElementById('pair').onclick=function(){prefs.server=document.getElementById('server').value.replace(/\/$/,'');localStorage.server=prefs.server;request('/api/devices/pair/request','POST',{name:'Samsung '+safeModel(),manufacturer:'Samsung',model:safeModel(),platform:'tizen',appVersion:'1.2.2',capabilities:capabilities()},false).then(function(result){document.getElementById('code').textContent=result.code;document.getElementById('message').textContent='Voer de code in bij Dashboard → TV en afspeelapparaten';poll(result.deviceId,result.pairingSecret)}).catch(showError)}}
function poll(id,secret){var timer=setInterval(function(){request('/api/devices/pair/claim','POST',{deviceId:id,pairingSecret:secret},false).then(function(result){if(result.status==='approved'){clearInterval(timer);prefs.token=result.token;localStorage.deviceToken=result.token;library()}else if(result.status==='expired'){clearInterval(timer);showError(new Error('Koppelcode verlopen.'))}}).catch(showError)},2000)}
function library(){request('/api/device/library','GET',null,true).then(function(items){root.innerHTML='<h2>Bibliotheek</h2><div class="grid">'+items.map(function(item){return '<button class="card" data-id="'+item.id+'"><b>'+escapeHtml(item.seriesTitle||item.title)+'</b><br><span>'+(item.kind==='episode'?'S'+item.season+' A'+item.episode:item.year||'')+'</span><p class="technical">'+(item.height||'?')+'p · '+(item.hdrType||'sdr')+(item.atmos?' · Atmos':'')+'</p></button>'}).join('')+'</div>';Array.prototype.forEach.call(document.querySelectorAll('.card'),function(card){card.onclick=function(){play(Number(card.dataset.id))}});var first=document.querySelector('.card');if(first)first.focus()}).catch(function(error){if(/token/i.test(error.message)){localStorage.removeItem('deviceToken');prefs.token='';pair()}else showError(error)})}
function play(id){request('/api/device/media/'+id+'/decision','POST',{quality:'auto',network:'lan'},true).then(function(result){currentMediaId=id;var object=document.getElementById('av-player');object.style.display='block';webapis.avplay.close();webapis.avplay.open(result.urls.playback);webapis.avplay.setDisplayRect(0,0,1920,1080);webapis.avplay.setListener({onbufferingstart:function(){},onbufferingcomplete:function(){},onstreamcompleted:function(){stop()},oncurrentplaytime:function(ms){if(ms%10000<500)progress(ms)},onerror:function(e){showError(new Error(e))}});webapis.avplay.prepareAsync(function(){webapis.avplay.play()},showError)}).catch(showError)}
function progress(ms){if(!currentMediaId)return;var duration=0;try{duration=webapis.avplay.getDuration()}catch(e){}request('/api/device/media/'+currentMediaId+'/progress','PUT',{position:ms/1000,duration:duration/1000},true).catch(function(){})}
function pollCommands(){if(!prefs.token)return;request('/api/device/commands','GET',null,true).then(function(result){(result.items||[]).forEach(function(entry){var p=entry.payload||{};try{if(entry.command==='play')webapis.avplay.play();else if(entry.command==='pause')webapis.avplay.pause();else if(entry.command==='stop')stop();else if(entry.command==='seek'){if(p.positionSeconds!=null)webapis.avplay.seekTo(Number(p.positionSeconds)*1000);else if(Number(p.deltaSeconds)>0)webapis.avplay.jumpForward(Number(p.deltaSeconds)*1000);else webapis.avplay.jumpBackward(Math.abs(Number(p.deltaSeconds))*1000)}else if(entry.command==='disconnect'){localStorage.removeItem('deviceToken');prefs.token='';stop();pair()}else if(entry.command==='load'&&p.mediaId)play(Number(p.mediaId))}catch(e){}request('/api/device/commands/'+entry.id+'/ack','POST',{},true).catch(function(){})})}).catch(function(){})}
function stop(){try{webapis.avplay.stop();webapis.avplay.close()}catch(e){}document.getElementById('av-player').style.display='none';currentMediaId=0;library()}
function safeModel(){try{return webapis.productinfo.getRealModel()}catch(e){return 'Smart TV'}}function showError(e){document.getElementById('status').textContent=e.message||String(e)}function escapeHtml(v){return String(v||'').replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
document.addEventListener('keydown',function(e){if(!currentMediaId)return;if(e.keyCode===10009)stop();else if(e.keyCode===415)webapis.avplay.play();else if(e.keyCode===19)webapis.avplay.pause();else if(e.keyCode===413)stop();else if(e.keyCode===417)webapis.avplay.jumpForward(30000);else if(e.keyCode===412)webapis.avplay.jumpBackward(30000)});try{tizen.tvinputdevice.registerKeyBatch(['MediaPlay','MediaPause','MediaStop','MediaFastForward','MediaRewind'])}catch(e){}setInterval(pollCommands,2000);if(prefs.token)library();else pair();
})();
