import { useEffect,useState } from 'react';
import { api,patch,post,put } from './api';

type Provider={id:'tvmaze'|'omdb'|'local_nfo'|'embedded'|'manual';label:string;enabled:boolean;configured:boolean;available:boolean;attribution?:string;informationUrl?:string;lastSuccessAt?:string;lastError?:string;rateLimitedUntil?:string;requestsToday:number;cacheHits:number;cacheMisses:number;failures:number;remainingLocalRequests?:number};
type MetadataSettingsData={providers:Provider[];secrets:{omdbConfigured:boolean;omdbKeyMasked:string;storage:string};movieOrder:Provider['id'][];seriesOrder:Provider['id'][];cacheDays:number;omdbLocalDailyLimit:number;metadataStrategy:'local_first'|'online_first'|'local_only'};

export default function MetadataSettings(){
  const[data,setData]=useState<MetadataSettingsData|null>(null);const[key,setKey]=useState('');const[message,setMessage]=useState('');const[error,setError]=useState('');const[drag,setDrag]=useState<Provider['id']|null>(null);
  const load=()=>api<MetadataSettingsData>('/metadata/providers').then(setData);
  useEffect(()=>{void load()},[]);
  async function act(fn:()=>Promise<unknown>,ok:string){setError('');setMessage('');try{await fn();setMessage(ok);await load()}catch(value:any){setError(value.message)}}
  async function toggle(provider:Provider){await act(()=>patch(`/metadata/providers/${provider.id}`,{enabled:!provider.enabled}),`${provider.label} is ${provider.enabled?'uitgeschakeld':'ingeschakeld'}.`)}
  async function reorder(kind:'movie'|'series',target:Provider['id']){if(!data||!drag||drag===target)return;const keyName=kind==='movie'?'movieOrder':'seriesOrder';const order=[...data[keyName]];order.splice(order.indexOf(drag),1);order.splice(order.indexOf(target),0,drag);setDrag(null);await act(()=>put(`/metadata/provider-order/${kind}`,{order}),'Provider-volgorde opgeslagen.')}
  if(!data)return <section className="panel"><p>Metadataproviders laden…</p></section>;
  const labels=Object.fromEntries(data.providers.map(provider=>[provider.id,provider.label]));
  return <section className="panel span-2 metadata-settings"><div className="panel-heading"><div><h2>Metadata</h2><p>TVmaze voor series, OMDb voor films en lokale NFO/bestandsmetadata als privacyvriendelijke fallback.</p></div><button className="secondary" onClick={()=>void load()}>Vernieuwen</button></div>
    {(message||error)&&<div className={`alert ${error?'error':'success'}`}>{error||message}</div>}
    <div className="provider-grid">{data.providers.map(provider=><article className="provider-card" key={provider.id}><header><div><strong>{provider.label}</strong><small>{provider.configured?'Geconfigureerd':'Niet geconfigureerd'} · {provider.available?'Beschikbaar':'Niet beschikbaar'}</small></div><input aria-label={`${provider.label} inschakelen`} type="checkbox" checked={provider.enabled} disabled={provider.id==='manual'} onChange={()=>void toggle(provider)}/></header><div className="provider-stats"><span>{provider.requestsToday} verzoeken vandaag</span><span>{provider.cacheHits} cachetreffers / {provider.cacheMisses} missers</span>{provider.remainingLocalRequests!==undefined&&<span>{provider.remainingLocalRequests} lokaal resterend</span>}<span>{provider.lastSuccessAt?`Laatst geslaagd: ${new Date(provider.lastSuccessAt).toLocaleString('nl-NL')}`:'Nog niet succesvol verbonden'}</span>{provider.rateLimitedUntil&&<span>Begrensd tot {new Date(provider.rateLimitedUntil).toLocaleString('nl-NL')}</span>}</div>{provider.lastError&&<small className="provider-error">{provider.lastError}</small>}<div className="button-row"><button className="secondary" onClick={()=>act(()=>post<any>(`/metadata/providers/${provider.id}/test`).then(result=>{if(!result.ok)throw new Error(result.message);return result}),`${provider.label} is bereikbaar.`)}>Verbinding testen</button>{provider.informationUrl&&<a className="help-link" href={provider.informationUrl} target="_blank" rel="noreferrer">Informatie ↗</a>}</div>{provider.attribution&&<small>{provider.attribution}</small>}</article>)}</div>
    <div className="metadata-config-grid"><div><h3>OMDb API-key</h3><p>Optioneel voor films. De sleutel staat alleen in een beveiligd lokaal bestand en wordt nooit teruggestuurd.</p><label>API-key<input type="password" autoComplete="off" value={key} onChange={event=>setKey(event.target.value)} placeholder={data.secrets.omdbConfigured?data.secrets.omdbKeyMasked:'Voer je OMDb API-key in'}/></label><div className="button-row"><button className="primary" disabled={!key.trim()} onClick={()=>act(()=>put('/metadata/omdb-key',{key}).then(()=>setKey('')),'OMDb API-key is getest en lokaal opgeslagen.')}>Testen en opslaan</button>{data.secrets.omdbConfigured&&<button className="text-danger" onClick={()=>act(()=>api('/metadata/omdb-key',{method:'DELETE'}),'OMDb API-key verwijderd.')}>Verwijderen</button>}</div><a className="help-link" href="https://www.omdbapi.com/apikey.aspx" target="_blank" rel="noreferrer">OMDb API-key aanvragen ↗</a></div>
      <div><h3>Voorkeur, cache en limiet</h3><label>Metadata-voorkeur<select value={data.metadataStrategy} onChange={event=>setData({...data,metadataStrategy:event.target.value as MetadataSettingsData['metadataStrategy']})}><option value="local_first">Lokale metadata eerst</option><option value="online_first">Online providers eerst</option><option value="local_only">Alleen lokale metadata</option></select></label><label>Bewaar providerresponses (dagen)<input type="number" min="1" max="365" value={data.cacheDays} onChange={event=>setData({...data,cacheDays:Number(event.target.value)})}/></label><label>Lokale OMDb-daglimiet<input type="number" min="1" max="100000" value={data.omdbLocalDailyLimit} onChange={event=>setData({...data,omdbLocalDailyLimit:Number(event.target.value)})}/></label><div className="button-row"><button className="primary" onClick={()=>act(()=>patch('/settings',{metadataCacheDays:data.cacheDays,omdbLocalDailyLimit:data.omdbLocalDailyLimit,metadataStrategy:data.metadataStrategy}),'Metadata-instellingen opgeslagen.')}>Opslaan</button><button className="secondary" onClick={()=>act(()=>api('/metadata/cache',{method:'DELETE'}),'Metadata- en afbeeldingscache geleegd.')}>Cache legen</button><button className="secondary" onClick={()=>act(()=>post('/metadata/queue/retry'),'Mislukte en te controleren items staan opnieuw in de wachtrij.')}>Opnieuw proberen</button></div></div></div>
    <div className="provider-order"><h3>Provider-prioriteit</h3><p>Sleep de kaarten om de volgorde te veranderen. Handmatige gegevens en vergrendelde velden blijven altijd behouden.</p>{(['movie','series'] as const).map(kind=><div key={kind}><strong>{kind==='movie'?'Films':'Series'}</strong><div>{data[kind==='movie'?'movieOrder':'seriesOrder'].map(id=><button draggable onDragStart={()=>setDrag(id)} onDragOver={event=>event.preventDefault()} onDrop={()=>void reorder(kind,id)} key={id}>{labels[id]}</button>)}</div></div>)}</div>
  </section>
}
