import { useCallback, useEffect, useMemo, useState } from 'react';
import { api, patch, post, type Settings } from './api';

type Section='overview'|'streams'|'libraries'|'transcoding'|'live-tv'|'remote'|'backups'|'database'|'logs'|'updates'|'system'|'about';
const sections:[Section,string][]=[['overview','Overzicht'],['streams','Actieve streams'],['libraries','Bibliotheken'],['transcoding','Transcoding'],['live-tv','Live TV en DVR'],['remote','Externe toegang'],['backups','Back-ups'],['database','Database en herstel'],['logs','Logboeken'],['updates','Updates'],['system','Systeeminformatie'],['about','Over ThuisHub']];

function bytes(value=0){if(value<1024)return`${value} B`;if(value<1048576)return`${(value/1024).toFixed(1)} KB`;if(value<1073741824)return`${(value/1048576).toFixed(1)} MB`;return`${(value/1073741824).toFixed(1)} GB`}
function duration(seconds=0){const days=Math.floor(seconds/86400);const hours=Math.floor(seconds%86400/3600);return days?`${days}d ${hours}u`:`${hours}u ${Math.floor(seconds%3600/60)}m`}

export default function ServerDashboard({settings,onSettingsChanged}:{settings:Settings;onSettingsChanged:()=>Promise<void>}){
  const requested=(new URLSearchParams(location.search).get('section')||'overview') as Section;
  const [section,setSection]=useState<Section>(sections.some(([id])=>id===requested)?requested:'overview');
  const [dashboard,setDashboard]=useState<any>(null);const[backups,setBackups]=useState<any>(null);const[database,setDatabase]=useState<any>(null);const[logs,setLogs]=useState<any>(null);const[tailscale,setTailscale]=useState<any>(null);const[updates,setUpdates]=useState<any>(null);
  const [message,setMessage]=useState('');const[error,setError]=useState('');const[busy,setBusy]=useState(false);const[logFilter,setLogFilter]=useState({category:'',level:'',search:'',date:''});
  const load=useCallback(async()=>{const[d,b,db,l,t,u]=await Promise.all([api('/dashboard'),api('/backups'),api('/database/status'),api('/logs'),api('/tailscale'),api('/updates')]);setDashboard(d);setBackups(b);setDatabase(db);setLogs(l);setTailscale(t);setUpdates(u)},[]);
  useEffect(()=>{void load().catch(e=>setError(e.message))},[load]);
  async function action(fn:()=>Promise<any>,success:string){setBusy(true);setError('');setMessage('');try{const result=await fn();setMessage(result?.message||success);await load()}catch(e:any){setError(e.message)}finally{setBusy(false)}}
  const filteredLogs=useMemo(()=>logs?.items?.filter((entry:any)=>(!logFilter.category||entry.category===logFilter.category)&&(!logFilter.level||entry.level===logFilter.level)&&(!logFilter.date||entry.timestamp.startsWith(logFilter.date))&&(!logFilter.search||JSON.stringify(entry).toLowerCase().includes(logFilter.search.toLowerCase())))||[],[logs,logFilter]);
  if(!dashboard)return <section className="dashboard-page"><div className="spinner"/>{error&&<div className="alert error">{error}</div>}</section>;
  return <section className="dashboard-page"><header className="dashboard-header"><img src="/brand/thuishub-logo.png" alt="ThuisHub"/><div><p className="eyebrow">SERVERDASHBOARD</p><h1>ThuisHub beheren</h1><span>Versie {dashboard.version} · {dashboard.serverStatus==='online'?'Online':'Offline'}</span></div><button className="secondary" onClick={()=>void load()}>Vernieuwen</button></header>
    {(message||error)&&<div className={`alert ${error?'error':'success'}`}>{error||message}</div>}
    <div className="dashboard-layout"><nav className="dashboard-nav">{sections.map(([id,label])=><button key={id} className={section===id?'active':''} onClick={()=>setSection(id)}>{label}</button>)}</nav><main className="dashboard-content">
      {section==='overview'&&<><Panel title="Statusoverzicht"><div className="metric-grid"><Metric label="Versie" value={dashboard.version}/><Metric label="Uptime" value={duration(dashboard.uptimeSeconds)}/><Metric label="Database" value={dashboard.database.ok?'In orde':'Probleem'}/><Metric label="Laatste back-up" value={dashboard.lastBackup?new Date(dashboard.lastBackup.createdAt).toLocaleString('nl-NL'):'Nog geen'}/><Metric label="Tailscale" value={dashboard.tailscale.serveActive?'Actief':'Niet actief'}/><Metric label="Actieve streams" value={dashboard.activity.length}/><Metric label="Gegevensopslag" value={bytes(dashboard.storage.dataBytes)}/><Metric label="Update" value={dashboard.update.available?dashboard.update.version:'Actueel'}/></div></Panel><Panel title="Bibliotheek"><div className="metric-grid"><Metric label="Films" value={dashboard.libraryCounts.movies}/><Metric label="Series" value={dashboard.libraryCounts.series}/><Metric label="Muziekalbums" value={dashboard.libraryCounts.albums}/><Metric label="Foto’s" value={dashboard.libraryCounts.photos}/></div></Panel>{dashboard.warnings.length>0&&<Panel title="Waarschuwingen"><ul className="warning-list">{dashboard.warnings.map((warning:string)=><li key={warning}>{warning}</li>)}</ul></Panel>}</>}
      {section==='streams'&&<Panel title="Actieve streams">{dashboard.activity.length?<div className="data-list">{dashboard.activity.map((item:any)=><div key={`${item.userId}-${item.mediaId}`}><strong>{item.title||`Media ${item.mediaId}`}</strong><span>{item.state} · {Math.round(item.position||0)} seconden</span></div>)}</div>:<Empty text="Er zijn momenteel geen actieve streams."/>}</Panel>}
      {section==='libraries'&&<Panel title="Bibliotheken"><div className="metric-grid"><Metric label="Films" value={dashboard.libraryCounts.movies}/><Metric label="Series" value={dashboard.libraryCounts.series}/><Metric label="Albums" value={dashboard.libraryCounts.albums}/><Metric label="Foto’s" value={dashboard.libraryCounts.photos}/><Metric label="Mediagrootte" value={bytes(dashboard.storage.libraryBytes)}/></div></Panel>}
      {section==='transcoding'&&<><Panel title="Transcoding"><div className="metric-grid"><Metric label="Encoder" value={dashboard.encoder.codec}/><Metric label="Hardware" value={dashboard.encoder.hardware?'GPU':'CPU'}/><Metric label="Videokaarten" value={dashboard.gpus.length}/><Metric label="Taken" value={dashboard.optimizations.length}/></div><div className="data-list">{dashboard.gpus.map((gpu:string)=><div key={gpu}><strong>{gpu}</strong></div>)}</div></Panel><Panel title="Optimalisaties">{dashboard.optimizations.length?<div className="data-list">{dashboard.optimizations.map((job:any)=><div key={job.id}><strong>{job.seriesTitle||job.title}</strong><span>{job.profile} · {job.status} · {Math.round(job.progress)}%</span></div>)}</div>:<Empty text="Geen optimalisaties actief."/>}</Panel></>}
      {section==='live-tv'&&<Panel title="Live TV en DVR"><p>Live TV, XMLTV en DVR blijven beschikbaar via de pagina Live TV. Geplande en actieve opnames worden door de achtergrondplanner bewaakt.</p><button className="secondary" onClick={()=>location.href='/?view=live'}>Live TV openen</button></Panel>}
      {section==='remote'&&<Panel title="Externe toegang via Tailscale"><Status ok={tailscale.connected&&tailscale.serveActive} text={tailscale.message}/><div className="detail-table"><span>Computernaam<b>{tailscale.computerName}</b></span><span>Lokale URL<b>{tailscale.localUrl}</b></span><span>Tailscale HTTPS-URL<b>{tailscale.httpsUrl||'Niet beschikbaar'}</b></span><span>Verbinding<b>{tailscale.connection}</b></span></div><div className="button-row"><button className="primary" disabled={!tailscale.httpsUrl} onClick={()=>navigator.clipboard.writeText(tailscale.httpsUrl).then(()=>setMessage('Tailscale-URL gekopieerd.'))}>URL kopiëren</button><a className="secondary" href="https://tailscale.com/download" target="_blank" rel="noreferrer">Tailscale-instructies</a></div><p className="dashboard-note">ThuisHub opent geen routerpoorten en gebruikt geen Funnel. Schakel Serve bewust in met <code>tailscale serve --bg 8787</code>.</p></Panel>}
      {section==='backups'&&<><Panel title="Back-upinstellingen"><div className="form-grid"><label>Schema<select value={settings.automaticBackups} onChange={e=>void action(()=>patch('/settings',{automaticBackups:e.target.value}).then(onSettingsChanged),'Back-upschema opgeslagen.')}><option value="off">Uit</option><option value="daily">Dagelijks</option><option value="weekly">Wekelijks</option></select></label><label>Maximaal bewaren<input type="number" min="1" max="100" value={settings.backupRetention} onChange={e=>void action(()=>patch('/settings',{backupRetention:Number(e.target.value)}).then(onSettingsChanged),'Bewaarlimiet opgeslagen.')}/></label><label className="span-2">Back-uplocatie<input defaultValue={settings.backupLocation} onBlur={e=>void action(()=>patch('/settings',{backupLocation:e.target.value}).then(onSettingsChanged),'Back-uplocatie opgeslagen.')}/></label></div><button className="primary" disabled={busy} onClick={()=>void action(()=>post('/backups'),'Handmatige back-up gemaakt.')}>Nu back-up maken</button></Panel><Panel title="Beschikbare back-ups">{backups.items.length?<div className="backup-list">{backups.items.map((backup:any)=><div key={backup.name}><span><strong>{backup.name}</strong><small>{new Date(backup.createdAt).toLocaleString('nl-NL')} · {bytes(backup.bytes)}</small></span><a href={`/api/backups/${encodeURIComponent(backup.name)}/download`}>Exporteren</a><button onClick={()=>void action(()=>post(`/backups/${encodeURIComponent(backup.name)}/verify`),'Back-up gecontroleerd.')}>Controleren</button><button className="danger-button" onClick={()=>{if(confirm('Deze back-up terugzetten? Eerst wordt automatisch een noodback-up gemaakt.'))void action(()=>post(`/backups/${encodeURIComponent(backup.name)}/restore`,{confirm:true}),'Herstel gepland.')}}>Terugzetten</button></div>)}</div>:<Empty text="Er zijn nog geen back-ups."/>}</Panel></>}
      {section==='database'&&<><Panel title="Database-integriteit"><Status ok={database.ok} text={database.ok?'De database is in orde.':'De database lijkt beschadigd.'}/><p className="technical"><code>{database.file}</code></p><div className="button-row"><button className="primary" onClick={()=>void action(()=>post('/database/check'),'Integriteitscontrole voltooid.')}>Integriteit controleren</button><a className="secondary" href="/api/database/export">Database exporteren</a><button className="secondary" onClick={()=>{if(confirm('Herstelpoging uitvoeren? Er wordt eerst een noodback-up gemaakt.'))void action(()=>post('/database/repair',{confirm:true}),'Herstelpoging voltooid.')}}>Herstelpoging</button><button className="secondary" onClick={()=>{if(confirm('Bibliotheek opnieuw indexeren? Gebruikers en instellingen blijven behouden.'))void action(()=>post('/database/rebuild-library',{confirm:true}),'Herindexering gestart.')}}>Bibliotheek opnieuw opbouwen</button></div><details><summary>Technische details</summary><pre>{JSON.stringify(database,null,2)}</pre></details></Panel></>}
      {section==='logs'&&<Panel title="Logboeken"><div className="log-filters"><select value={logFilter.category} onChange={e=>setLogFilter({...logFilter,category:e.target.value})}><option value="">Alle categorieën</option>{['server','application','database','updater','transcoding','streaming','live-tv','tailscale','backups','crash'].map(x=><option key={x}>{x}</option>)}</select><select value={logFilter.level} onChange={e=>setLogFilter({...logFilter,level:e.target.value})}><option value="">Alle niveaus</option>{['DEBUG','INFO','WARNING','ERROR','CRITICAL'].map(x=><option key={x}>{x}</option>)}</select><input type="date" value={logFilter.date} onChange={e=>setLogFilter({...logFilter,date:e.target.value})}/><input placeholder="Zoeken…" value={logFilter.search} onChange={e=>setLogFilter({...logFilter,search:e.target.value})}/></div><div className="form-grid"><label>Maximale logopslag (MB)<input type="number" min="10" max="2048" defaultValue={settings.maxLogStorageMb} onBlur={e=>void action(()=>patch('/settings',{maxLogStorageMb:Number(e.target.value)}).then(onSettingsChanged),'Logopslaglimiet opgeslagen.')}/></label></div><div className="button-row"><a className="secondary" href="/api/logs/download">Downloaden</a><button className="secondary" onClick={()=>navigator.clipboard.writeText(filteredLogs.map((x:any)=>JSON.stringify(x)).join('\n'))}>Kopiëren</button><button className="secondary" onClick={()=>void post('/logs/open-folder')}>Logmap openen</button><button className="danger-button" onClick={()=>{if(confirm('Alle geroteerde logboeken opschonen?'))void action(()=>api('/logs',{method:'DELETE'}),'Logboeken opgeschoond.')}}>Opschonen</button></div><div className="log-view">{filteredLogs.slice(0,300).map((entry:any,index:number)=><div key={`${entry.timestamp}-${index}`} data-level={entry.level}><time>{new Date(entry.timestamp).toLocaleString('nl-NL')}</time><b>{entry.level}</b><span>{entry.category}</span><p>{entry.message}</p></div>)}</div><small>{bytes(logs.bytes)} in {logs.directory}</small></Panel>}
      {section==='updates'&&<Panel title="Updates"><div className="detail-table"><span>Huidige versie<b>{updates.currentVersion}</b></span><span>Kanaal<b>{updates.channel}</b></span><span>Laatste controle<b>{updates.lastCheckAt?new Date(updates.lastCheckAt).toLocaleString('nl-NL'):'Nog niet'}</b></span><span>Status<b>{updates.lastResult.available?`Versie ${updates.lastResult.version} beschikbaar`:'Actueel of niet geconfigureerd'}</b></span></div><div className="form-grid"><label>Updatekanaal<select value={settings.updateChannel} onChange={e=>void action(()=>patch('/settings',{updateChannel:e.target.value}).then(onSettingsChanged),'Updatekanaal opgeslagen.')}><option value="stable">Stabiel</option><option value="beta">Bèta</option><option value="development">Ontwikkeling</option></select></label><label>Manifest-URL<input type="url" defaultValue={settings.updateManifestUrl} onBlur={e=>void action(()=>patch('/settings',{updateManifestUrl:e.target.value}).then(onSettingsChanged),'Updatebron opgeslagen.')}/></label><label><input type="checkbox" checked={settings.automaticUpdateCheck} onChange={e=>void action(()=>patch('/settings',{automaticUpdateCheck:e.target.checked}).then(onSettingsChanged),'Automatische updatecontrole opgeslagen.')}/> Bij opstarten controleren</label></div><div className="button-row"><button className="primary" onClick={()=>void action(()=>post('/updates/check'),'Updatecontrole voltooid.')}>Controleren op updates</button>{updates.lastResult.available&&<button className="secondary" onClick={()=>{if(confirm(`ThuisHub ${updates.lastResult.version} downloaden en met SHA-256 controleren?`))void action(()=>post('/updates/download',{confirm:true,manifest:updates.lastResult}),'Update gecontroleerd en gedownload.')}}>Update downloaden</button>}</div>{updates.lastResult.releaseNotes&&<div className="release-notes"><h3>Release notes</h3><p>{updates.lastResult.releaseNotes}</p><small>{updates.lastResult.size?bytes(updates.lastResult.size):'Grootte onbekend'} · {updates.lastResult.channel}</small></div>}<p className="dashboard-note">Updates worden nooit automatisch geïnstalleerd. Een download wordt eerst met SHA-256 gecontroleerd.</p></Panel>}
      {section==='system'&&<Panel title="Systeeminformatie"><div className="detail-table"><span>Serverstatus<b>{dashboard.serverStatus}</b></span><span>Versie<b>{dashboard.version}</b></span><span>Encoder<b>{dashboard.encoder.codec}</b></span><span>Data-opslag<b>{bytes(dashboard.storage.dataBytes)}</b></span><span>Logopslag<b>{bytes(dashboard.storage.logBytes)}</b></span><span>Databasebestand<b>{dashboard.database.file}</b></span></div></Panel>}
      {section==='about'&&<Panel title="Over ThuisHub"><div className="about-block"><img src="/brand/thuishub-logo.png" alt="ThuisHub"/><h2>ThuisHub {dashboard.version}</h2><p>Je eigen lokale mediaserver voor films, series, muziek, foto’s en Live TV. Geen abonnement en geen standaard openbare toegang.</p></div></Panel>}
    </main></div></section>
}

function Panel({title,children}:{title:string;children:React.ReactNode}){return <section className="dashboard-panel"><h2>{title}</h2>{children}</section>}
function Metric({label,value}:{label:string;value:string|number}){return <span className="metric"><strong>{value}</strong><small>{label}</small></span>}
function Empty({text}:{text:string}){return <p className="dashboard-empty">{text}</p>}
function Status({ok,text}:{ok:boolean;text:string}){return <div className={`status-banner ${ok?'ok':'warning'}`}><i/>{text}</div>}

